import {
  IOrganization,
  IServicePackage,
  IDurationOption,
  IPackageType,
  IExtraPackage,
  IBankAccount,
} from "./types";

/**
 * Thông tin tài khoản ngân hàng fallback
 */
export const BANK_ACCOUNTS: Record<string, IBankAccount> = {
  BBH: {
    bank_bin: 970407,
    account: "19036252323010",
    name: "CTCP Công nghệ Chatbot Việt Nam",
    bank: "Techcombank - Ngân hàng Kỹ thương Việt Nam - Chi nhánh Hà Thành",
    code: "BBH_TCB",
  },
  A_TUNG_TIMO: {
    bank_bin: 963388,
    account: "9021103769279",
    name: "Nguyễn Đình Tùng",
    bank: "Ngân hàng số Timo by Ban Viet Bank (Timo by Ban Viet Bank)",
    code: "TUNG_TIMO",
  },
};

export const BANK_ACCOUNTS_NAME = "VM BOTBANHANGHCM";

/** Giá trị đại diện cho không giới hạn */
const UNLIMITED_VALUE = 9999999999999;
/** Số mili giây trong 1 tháng */
const MONTH_IN_MS = 1000 * 60 * 60 * 24 * 30;

/**
 * Danh sách các gói đăng ký chính
 */
export const SUBSCRIPTION_PACKAGES: IServicePackage[] = [
  /** Gói miễn phí */
  // {
  //   id: "free",
  //   name: "Gói FREE",
  //   price: 0,
  //   type: IPackageType.SUBSCRIPTION,
  //   description: "Gói miễn phí, sản phẩm phễu",
  //   duration: UNLIMITED_VALUE,
  //   page: 2,
  //   staff: 1,
  //   client: 600,
  //   fau: 1000,
  //   aiText: 100000,
  //   aiImage: 100,
  //   aiSound: 100 * 60,
  //   aiVideo: 0,
  // },
  /** Gói dùng thử */
  // {
  //   id: "trial",
  //   name: "Gói TRIAL",
  //   price: 0,
  //   type: IPackageType.SUBSCRIPTION,
  //   description: "Gói dùng thử 7 ngày - thiết lập giống gói PRO",
  //   duration: 1000 * 60 * 60 * 24 * 7,
  //   page: 5,
  //   staff: 10,
  //   client: UNLIMITED_VALUE,
  //   fau: 10000,
  //   aiText: 10000000,
  //   aiImage: 1000,
  //   aiSound: 1000 * 60,
  //   aiVideo: 10 * 60,
  // },
  // {
  //   id: "trial_lite",
  //   name: "Gói TRIAL LITE",
  //   price: 0,
  //   type: IPackageType.SUBSCRIPTION,
  //   description: "Gói dùng thử 7 ngày - thiết lập giống gói LITE",
  //   duration: 1000 * 60 * 60 * 24 * 7,
  //   page: 3,
  //   staff: 3,
  //   client: UNLIMITED_VALUE,
  //   fau: 10000,
  //   aiText: 1000000,
  //   aiImage: 1000,
  //   aiSound: 1000 * 60,
  //   aiVideo: 10 * 60,
  // },
  // {
  //   id: "trial_business",
  //   name: "Gói TRIAL BUSINESS",
  //   price: 0,
  //   type: IPackageType.SUBSCRIPTION,
  //   description: "Gói dùng thử 7 ngày - thiết lập giống gói BUSINESS",
  //   duration: 1000 * 60 * 60 * 24 * 7,
  //   page: 40,
  //   staff: 40,
  //   client: UNLIMITED_VALUE,
  //   fau: 50000,
  //   aiText: 50000000,
  //   aiImage: 10000,
  //   aiSound: 10000 * 60,
  //   aiVideo: 100 * 60,
  // },
  /** Gói chính thức */
  {
    id: "LITE",
    name: "Gói LITE",
    price: 199000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói khởi đầu cho doanh nghiệp nhỏ",
    duration: MONTH_IN_MS,
    page: 3,
    staff: 3,
    client: UNLIMITED_VALUE,
    fau: 10000,
    aiText: 1000000,
    aiImage: 1000,
    aiSound: 1000 * 60,
    aiVideo: 10 * 60,
  },
  {
    id: "PRO",
    name: "Gói PRO",
    price: 480000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói chuyên nghiệp cho doanh nghiệp vừa và nhỏ",
    duration: MONTH_IN_MS,
    page: 5,
    staff: 10,
    client: UNLIMITED_VALUE,
    fau: 10000,
    aiText: 10000000,
    aiImage: 1000,
    aiSound: 1000 * 60,
    aiVideo: 10 * 60,
  },
  {
    id: "PRO_2",
    name: "Gói PRO 2",
    price: 960000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói của Tuấn - chỉ tăng FAU lên 30K",
    duration: MONTH_IN_MS,
    page: 5,
    staff: 10,
    client: UNLIMITED_VALUE,
    fau: 30000,
    aiText: 10000000,
    aiImage: 1000,
    aiSound: 1000 * 60,
    aiVideo: 10 * 60,
  },
  {
    id: "PRO_2X",
    name: "Gói PRO 2X",
    price: 960000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói PRO gấp đôi - tăng gấp đôi mọi thông số",
    duration: MONTH_IN_MS,
    page: 10,
    staff: 20,
    client: UNLIMITED_VALUE,
    fau: 20000,
    aiText: 20000000,
    aiImage: 2000,
    aiSound: 2000 * 60,
    aiVideo: 20 * 60,
  },
  {
    id: "PRO_3X",
    name: "Gói PRO 3X",
    price: 1440000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói PRO gấp ba - tăng gấp ba mọi thông số",
    duration: MONTH_IN_MS,
    page: 15,
    staff: 30,
    client: UNLIMITED_VALUE,
    fau: 30000,
    aiText: 30000000,
    aiImage: 3000,
    aiSound: 3000 * 60,
    aiVideo: 30 * 60,
  },
  {
    id: "MILK_1",
    name: "Gói MILK 1",
    price: 199000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói riêng a Tùng - shop khách bán sữa",
    duration: MONTH_IN_MS,
    page: 1,
    staff: 2,
    client: UNLIMITED_VALUE,
    fau: 10000,
    aiText: 10000000,
    aiImage: 1000,
    aiSound: 1000 * 60,
    aiVideo: 10 * 60,
  },
  {
    id: "BUSINESS",
    name: "Gói BUSINESS",
    price: 2600000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói dành cho doanh nghiệp lớn với đầy đủ tính năng",
    duration: MONTH_IN_MS,
    page: 40,
    staff: 40,
    client: UNLIMITED_VALUE,
    fau: 50000,
    aiText: 50000000,
    aiImage: 10000,
    aiSound: 10000 * 60,
    aiVideo: 100 * 60,
  },
  /** Gói không giới hạn */
  {
    id: "UNLIMITED_25",
    name: "Gói UNLIMITED 25M",
    price: 25000000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói không giới hạn 25M - có giới hạn 30 nhân viên",
    duration: MONTH_IN_MS * 12,
    page: UNLIMITED_VALUE,
    staff: 30,
    client: UNLIMITED_VALUE,
    fau: 50000,
    aiText: 10000000,
    aiImage: 1000,
    aiSound: 100 * 60,
    aiVideo: 10 * 60,
  },
  {
    id: "UNLIMITED_40",
    name: "Gói UNLIMITED 40M",
    price: 40000000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói không giới hạn 40M - có giới hạn 60 nhân viên",
    duration: MONTH_IN_MS * 12,
    page: UNLIMITED_VALUE,
    staff: 60,
    client: UNLIMITED_VALUE,
    fau: 50000,
    aiText: 10000000,
    aiImage: 1000,
    aiSound: 100 * 60,
    aiVideo: 10 * 60,
  },
  {
    id: "UNLIMITED_85",
    name: "Gói UNLIMITED 85M",
    price: 85000000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói không giới hạn 85M max - không giới hạn tất cả",
    duration: MONTH_IN_MS * 12,
    page: UNLIMITED_VALUE,
    staff: UNLIMITED_VALUE,
    client: UNLIMITED_VALUE,
    fau: 50000,
    aiText: 10000000,
    aiImage: 1000,
    aiSound: 100 * 60,
    aiVideo: 10 * 60,
  },
  /** Gói của a Tiến */
  {
    id: "CHATBOT_AI_BASE",
    name: "Gói CHATBOT AI BASE",
    price: 31200000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói AI cơ bản của a Tiến - 1 năm",
    duration: MONTH_IN_MS * 12,
    page: 24,
    staff: 20,
    client: UNLIMITED_VALUE,
    fau: 108000,
    aiText: 50000000,
    aiImage: 50000,
    aiSound: 50000 * 60,
    aiVideo: 5000 * 60,
  },
  {
    id: "CHATBOT_AI_BUSINESS_1_4",
    name: "Gói CHATBOT AI BUSINESS 1/4",
    price: 19200000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói AI Business 1/4 của a Tiến - 1 năm",
    duration: MONTH_IN_MS * 12,
    page: 20,
    staff: 8,
    client: UNLIMITED_VALUE,
    fau: 50000,
    aiText: 50000000,
    aiImage: 50000,
    aiSound: 50000,
    aiVideo: 5000 * 60,
  },
  {
    id: "CHATBOT_AI_BUSINESS",
    name: "Gói CHATBOT AI BUSINESS",
    price: 76800000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói AI Business của a Tiến - 1 năm",
    duration: MONTH_IN_MS * 12,
    page: 80,
    staff: 30,
    client: UNLIMITED_VALUE,
    fau: 200000,
    aiText: 200000000,
    aiImage: 200000,
    aiSound: 200000,
    aiVideo: 20000 * 60,
  },
  {
    id: "CHATBOT_AI_PRO",
    name: "Gói CHATBOT AI PRO",
    price: 161280000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói AI Pro của a Tiến - 1 năm",
    duration: MONTH_IN_MS * 12,
    page: 190,
    staff: 40,
    client: UNLIMITED_VALUE,
    fau: 300000,
    aiText: 40000000,
    aiImage: 40000,
    aiSound: 40000 * 60,
    aiVideo: 4000 * 60,
  },
  {
    id: "CHATBOT_AI_ENTERPRISE",
    name: "Gói CHATBOT AI ENTERPRISE",
    price: 382920000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói AI Enterprise của a Tiến - 1 năm",
    duration: MONTH_IN_MS * 12,
    page: 400,
    staff: 70,
    client: UNLIMITED_VALUE,
    fau: 1600000,
    aiText: 60000000,
    aiImage: 60000,
    aiSound: 60000 * 60,
    aiVideo: 6000 * 60,
  },
  /** Gói BOT cũ */
  {
    id: "CHATBOT_UNLIMITED_1_YEAR",
    name: "Gói CHATBOT UNLIMITED 1 NĂM",
    price: 25000000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói unli chatbot cũ - tặng 1 năm",
    duration: MONTH_IN_MS * 12,
    page: UNLIMITED_VALUE,
    staff: UNLIMITED_VALUE,
    client: UNLIMITED_VALUE,
    fau: 500000,
    aiText: 0,
    aiImage: 0,
    aiSound: 0,
    aiVideo: 0,
  },
  {
    id: "CHATBOT_UNLIMITED_N_YEAR",
    name: "Gói CHATBOT UNLIMITED VĨNH VIỄN",
    price: 25000000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói unli chatbot tiêu chuẩn - không giới hạn thời gian",
    duration: UNLIMITED_VALUE,
    page: UNLIMITED_VALUE,
    staff: UNLIMITED_VALUE,
    client: UNLIMITED_VALUE,
    fau: 500000,
    aiText: 0,
    aiImage: 0,
    aiSound: 0,
    aiVideo: 0,
  },
  {
    id: "CHATBOT_MARKETING_1_YEAR",
    name: "Gói CHATBOT MARKETING 1 NĂM",
    price: 3480000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói chatbot lẻ 1 năm - không có AI",
    duration: MONTH_IN_MS * 12,
    page: 1,
    staff: 10,
    client: UNLIMITED_VALUE,
    fau: 100000,
    aiText: 0,
    aiImage: 0,
    aiSound: 0,
    aiVideo: 0,
  },
  {
    id: "CHATBOT_LOYALTY_1_YEAR",
    name: "Gói CHATBOT LOYALTY 1 NĂM",
    price: 6708000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói chatbot lẻ 1 năm có app - không có AI",
    duration: MONTH_IN_MS * 12,
    page: 1,
    staff: 10,
    client: UNLIMITED_VALUE,
    fau: 100000,
    aiText: 0,
    aiImage: 0,
    aiSound: 0,
    aiVideo: 0,
  },
  /** Gói của Tuấn */
  {
    id: "BUSINESS_TUAN_GIAY_BIG_SIZE",
    name: "Gói BUSINESS TUẤN GIÀY BIG SIZE",
    price: 4160000,
    type: IPackageType.SUBSCRIPTION,
    description: "Gói riêng của Tuấn - 12 tháng: 49.920.000 VND",
    duration: MONTH_IN_MS,
    page: 15,
    staff: 15,
    client: UNLIMITED_VALUE,
    fau: 500000,
    aiText: 15000000,
    aiImage: 15000,
    aiSound: 15000 * 60,
    aiVideo: 150 * 60,
  },
];

/**
 * Danh sách gói mua thêm trang
 */
export const EXTRA_PAGE_PACKAGES: IExtraPackage[] = [
  {
    id: "extra_page_1",
    name: "Mua thêm 1 trang",
    price: 60000,
    type: IPackageType.EXTRA_PAGE,
    description:
      "Thêm 1 trang Facebook/Zalo vào hệ thống (2.000đ/ngày x 30 ngày)",
    quantity: 1,
    unit: "trang",
    pricePerUnit: 2000,
  },
  {
    id: "extra_page_5",
    name: "Mua thêm 5 trang",
    price: 300000,
    type: IPackageType.EXTRA_PAGE,
    description: "Thêm 5 trang Facebook/Zalo vào hệ thống",
    quantity: 5,
    unit: "trang",
    pricePerUnit: 2000,
  },
  {
    id: "extra_page_10",
    name: "Mua thêm 10 trang",
    price: 600000,
    type: IPackageType.EXTRA_PAGE,
    description: "Thêm 10 trang Facebook/Zalo vào hệ thống",
    quantity: 10,
    unit: "trang",
    pricePerUnit: 2000,
  },
];

/**
 * Danh sách gói mua thêm nhân viên
 */
export const EXTRA_STAFF_PACKAGES: IExtraPackage[] = [
  {
    id: "extra_staff_1",
    name: "Mua thêm 1 nhân viên",
    price: 30000,
    type: IPackageType.EXTRA_STAFF,
    description:
      "Thêm 1 tài khoản nhân viên vào hệ thống (1.000đ/ngày x 30 ngày)",
    quantity: 1,
    unit: "nhân viên",
    pricePerUnit: 1000,
  },
  {
    id: "extra_staff_5",
    name: "Mua thêm 5 nhân viên",
    price: 150000,
    type: IPackageType.EXTRA_STAFF,
    description: "Thêm 5 tài khoản nhân viên vào hệ thống",
    quantity: 5,
    unit: "nhân viên",
    pricePerUnit: 1000,
  },
  {
    id: "extra_staff_10",
    name: "Mua thêm 10 nhân viên",
    price: 300000,
    type: IPackageType.EXTRA_STAFF,
    description: "Thêm 10 tài khoản nhân viên vào hệ thống",
    quantity: 10,
    unit: "nhân viên",
    pricePerUnit: 1000,
  },
];

/**
 * Danh sách gói mua thêm FAU
 */
export const EXTRA_FAU_PACKAGES: IExtraPackage[] = [
  {
    id: "extra_fau_10k",
    name: "Mua thêm 10,000 FAU",
    price: 50000,
    type: IPackageType.EXTRA_FAU,
    description: "Thêm 10,000 FAU cho hệ thống",
    quantity: 10000,
    unit: "FAU",
    pricePerUnit: 50000 / 10000,
  },
  {
    id: "extra_fau_50k",
    name: "Mua thêm 50,000 FAU",
    price: 250000,
    type: IPackageType.EXTRA_FAU,
    description: "Thêm 50,000 FAU cho hệ thống",
    quantity: 50000,
    unit: "FAU",
    pricePerUnit: 50000 / 10000,
  },
  {
    id: "extra_fau_100k",
    name: "Mua thêm 100,000 FAU",
    price: 500000,
    type: IPackageType.EXTRA_FAU,
    description: "Thêm 100,000 FAU cho hệ thống",
    quantity: 100000,
    unit: "FAU",
    pricePerUnit: 50000 / 10000,
  },
];

/**
 * Danh sách gói mua thêm AI Text
 */
export const EXTRA_AI_TEXT_PACKAGES: IExtraPackage[] = [
  {
    id: "extra_ai_text_1m",
    name: "Mua thêm 1,000,000 ký tự",
    price: 25000,
    type: IPackageType.EXTRA_AI_TEXT,
    description: "Thêm 1,000,000 ký tự AI",
    quantity: 1000000,
    unit: "ký tự",
    pricePerUnit: 25000 / 1000000,
  },
  {
    id: "extra_ai_text_5m",
    name: "Mua thêm 5,000,000 ký tự",
    price: 125000,
    type: IPackageType.EXTRA_AI_TEXT,
    description: "Thêm 5,000,000 ký tự AI",
    quantity: 5000000,
    unit: "ký tự",
    pricePerUnit: 25000 / 1000000,
  },
  {
    id: "extra_ai_text_10m",
    name: "Mua thêm 10,000,000 ký tự",
    price: 250000,
    type: IPackageType.EXTRA_AI_TEXT,
    description: "Thêm 10,000,000 ký tự AI",
    quantity: 10000000,
    unit: "ký tự",
    pricePerUnit: 25000 / 1000000,
  },
];

/**
 * Danh sách gói mua thêm AI Image
 */
export const EXTRA_AI_IMAGE_PACKAGES: IExtraPackage[] = [
  {
    id: "extra_ai_image_1k",
    name: "Mua thêm 1,000 ảnh",
    price: 25000,
    type: IPackageType.EXTRA_AI_IMAGE,
    description: "Thêm 1,000 ảnh AI",
    quantity: 1000,
    unit: "ảnh",
    pricePerUnit: 25000 / 1000,
  },
  {
    id: "extra_ai_image_5k",
    name: "Mua thêm 5,000 ảnh",
    price: 125000,
    type: IPackageType.EXTRA_AI_IMAGE,
    description: "Thêm 5,000 ảnh AI",
    quantity: 5000,
    unit: "ảnh",
    pricePerUnit: 25000 / 1000,
  },
  {
    id: "extra_ai_image_10k",
    name: "Mua thêm 10,000 ảnh",
    price: 250000,
    type: IPackageType.EXTRA_AI_IMAGE,
    description: "Thêm 10,000 ảnh AI",
    quantity: 10000,
    unit: "ảnh",
    pricePerUnit: 25000 / 1000,
  },
];

/**
 * Danh sách gói mua thêm AI Sound
 */
export const EXTRA_AI_SOUND_PACKAGES: IExtraPackage[] = [
  {
    id: "extra_ai_sound_1k",
    name: "Mua thêm 1,000 phút âm thanh",
    price: 25000,
    type: IPackageType.EXTRA_AI_SOUND,
    description: "Thêm 1,000 phút âm thanh AI",
    quantity: 1000 * 60,
    unit: "phút",
    pricePerUnit: 25000 / (60 * 1000),
  },
  {
    id: "extra_ai_sound_5k",
    name: "Mua thêm 5,000 phút âm thanh",
    price: 125000,
    type: IPackageType.EXTRA_AI_SOUND,
    description: "Thêm 5,000 phút âm thanh AI",
    quantity: 5000 * 60,
    unit: "phút",
    pricePerUnit: 25000 / (60 * 1000),
  },
  {
    id: "extra_ai_sound_10k",
    name: "Mua thêm 10,000 phút âm thanh",
    price: 250000,
    type: IPackageType.EXTRA_AI_SOUND,
    description: "Thêm 10,000 phút âm thanh AI",
    quantity: 10000 * 60,
    unit: "phút",
    pricePerUnit: 25000 / (60 * 1000),
  },
];

/**
 * Danh sách gói mua thêm AI Video
 */
export const EXTRA_AI_VIDEO_PACKAGES: IExtraPackage[] = [
  {
    id: "extra_ai_video_10",
    name: "Mua thêm 10 phút video",
    price: 6000,
    type: IPackageType.EXTRA_AI_VIDEO,
    description: "Thêm 10 phút video AI",
    quantity: 10 * 60,
    unit: "phút",
    pricePerUnit: 6000 / (60 * 10),
  },
  {
    id: "extra_ai_video_50",
    name: "Mua thêm 50 phút video",
    price: 30000,
    type: IPackageType.EXTRA_AI_VIDEO,
    description: "Thêm 50 phút video AI",
    quantity: 50 * 60,
    unit: "phút",
    pricePerUnit: 6000 / (60 * 10),
  },
  {
    id: "extra_ai_video_100",
    name: "Mua thêm 100 phút video",
    price: 60000,
    type: IPackageType.EXTRA_AI_VIDEO,
    description: "Thêm 100 phút video AI",
    quantity: 100 * 60,
    unit: "phút",
    pricePerUnit: 6000 / (60 * 10),
  },
];

/**
 * Tất cả các gói đăng ký
 */
export const MOCK_PACKAGES: IServicePackage[] = SUBSCRIPTION_PACKAGES;

/**
 * Tất cả các gói mua thêm
 */
export const ALL_EXTRA_PACKAGES: IExtraPackage[] = [
  ...EXTRA_PAGE_PACKAGES,
  ...EXTRA_STAFF_PACKAGES,
  ...EXTRA_FAU_PACKAGES,
  ...EXTRA_AI_TEXT_PACKAGES,
  ...EXTRA_AI_IMAGE_PACKAGES,
  ...EXTRA_AI_SOUND_PACKAGES,
  ...EXTRA_AI_VIDEO_PACKAGES,
];

/**
 * Danh sách các tùy chọn thời hạn
 */
export const MOCK_DURATIONS: IDurationOption[] = [
  { months: 1, label: "1 tháng" },
  { months: 2, label: "2 tháng" },
  { months: 3, label: "3 tháng" },
  { months: 4, label: "4 tháng" },
  { months: 5, label: "5 tháng" },
  { months: 6, label: "6 tháng" },
  { months: 9, label: "9 tháng" },
  { months: 12, label: "12 tháng" },
  { months: 15, label: "15 tháng" },
  { months: 18, label: "18 tháng" },
  { months: 21, label: "21 tháng" },
  { months: 24, label: "24 tháng" },
  { months: 30, label: "30 tháng" },
  { months: 36, label: "36 tháng" },
];

/**
 * Dữ liệu giả định về tổ chức
 */
export const MOCK_DB: IOrganization[] = [
  {
    id: "1",
    orgId: "ORG-10293",
    name: "CÔNG TY ABC",
    balance: 500000,
    currentPackage: "FREE TIER",
    refName: null,
    refStatus: "Chưa có",
  },
  {
    id: "2",
    orgId: "ORG-99999",
    name: "CÔNG TY XYZ GLOBAL",
    balance: 12000000,
    currentPackage: "PRO",
    refName: "Sale Nguyen B",
    refStatus: "Đã gán",
  },
];

/**
 * Người dùng hiện tại
 */
export const CURRENT_USER = "Sale Nguyen A";
